"""Align the Emberkeeper voice clips to the tour script, word by word.

Reads every tour line (text + preText variants) straight out of lib/tour.tsx,
transcribes its voice clip with faster-whisper (word timestamps), aligns the
known script words to the heard words, and writes lib/tour-voice-timing.ts:
per clip, per text variant, a [start, end] second pair for every word. The
narration box uses those to reveal the line letter-exact with the voice.

Run from pyre-app/:  python scripts/align-voice.py
Re-run whenever voice clips or tour lines change.

Requires: pip install faster-whisper  (model downloads on first run)
"""

import json
import re
import sys
from difflib import SequenceMatcher
from pathlib import Path

APP = Path(__file__).resolve().parent.parent
TOUR = APP / "lib" / "tour.tsx"
OUT = APP / "lib" / "tour-voice-timing.ts"
VOICE_DIR = APP / "public"

LINE_RE = re.compile(
    r'text:\s*"([^"]+)",\s*preText:\s*"([^"]+)",\s*voice:\s*"([^"]+)"',
    re.DOTALL,
)


def norm(word: str) -> str:
    """Normalize a word for matching script to transcript ("$PYRE," -> "pyre")."""
    return re.sub(r"[^a-z0-9]", "", word.lower())


def align(script_words: list[str], heard: list) -> list[tuple[float, float]]:
    """Map each script word to a [start, end] via matched anchors; interpolate
    the unmatched stretches proportionally to word length."""
    s_norm = [norm(w) for w in script_words]
    h_norm = [norm(w.word) for w in heard]
    sm = SequenceMatcher(a=s_norm, b=h_norm, autojunk=False)

    spans: list[tuple[float, float] | None] = [None] * len(script_words)
    for block in sm.get_matching_blocks():
        for k in range(block.size):
            w = heard[block.b + k]
            spans[block.a + k] = (w.start, w.end)

    clip_end = heard[-1].end if heard else 0.0
    matched = sum(1 for s in spans if s)

    # Fill unmatched runs by spreading the surrounding gap across them,
    # weighted by word length (longer words take longer to say).
    i = 0
    while i < len(spans):
        if spans[i] is not None:
            i += 1
            continue
        j = i
        while j < len(spans) and spans[j] is None:
            j += 1
        gap_start = spans[i - 1][1] if i > 0 else (heard[0].start if heard else 0.0)
        gap_end = spans[j][0] if j < len(spans) else clip_end
        if gap_end <= gap_start:
            gap_end = gap_start
        weights = [max(2, len(script_words[k])) for k in range(i, j)]
        total = sum(weights)
        t = gap_start
        for k, wt in zip(range(i, j), weights):
            t2 = t + (gap_end - gap_start) * wt / total
            spans[k] = (t, t2)
            t = t2
        i = j

    # Enforce monotonic, non-degenerate spans.
    prev = 0.0
    fixed: list[tuple[float, float]] = []
    for s, e in spans:  # type: ignore[misc]
        s = max(s, prev)
        e = max(e, s)
        fixed.append((round(s, 2), round(e, 2)))
        prev = e
    print(f"    matched {matched}/{len(script_words)} words to the transcript")
    return fixed


def main() -> None:
    lines = LINE_RE.findall(TOUR.read_text(encoding="utf-8"))
    if not lines:
        sys.exit("No text/preText/voice blocks found in lib/tour.tsx")
    print(f"{len(lines)} voiced tour lines found in tour.tsx")

    from faster_whisper import WhisperModel

    print("loading whisper model (small, int8)...")
    model = WhisperModel("small", device="cpu", compute_type="int8")

    out: dict[str, list[list[list[float]]]] = {}
    for text, pre_text, voice in lines:
        clip = VOICE_DIR / voice.lstrip("/")
        if not clip.exists():
            sys.exit(f"missing clip: {clip}")
        print(f"{voice}")
        segments, _ = model.transcribe(
            str(clip),
            language="en",
            word_timestamps=True,
            initial_prompt=pre_text,
        )
        heard = [w for seg in segments for w in seg.words]
        print(f"    heard {len(heard)} words")

        variants = []
        seen: set[str] = set()
        for variant in (text, pre_text):
            if variant in seen:
                continue
            seen.add(variant)
            variants.append([list(p) for p in align(variant.split(" "), heard)])
        out[voice] = variants

    body = json.dumps(out, separators=(",", ":"))
    OUT.write_text(
        "/* AUTO-GENERATED by scripts/align-voice.py, do not edit by hand.\n"
        "   Word-level [start, end] seconds for every Emberkeeper voice clip,\n"
        "   one timing list per text variant of the line (launched text first,\n"
        "   preText second when it differs). The narration box picks the list\n"
        "   whose length matches the displayed line's word count and reveals\n"
        "   the words in step with the clip's playhead. */\n\n"
        "export const VOICE_TIMING: Record<string, [number, number][][]> =\n"
        f"  {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
